{
 "title": "Cloud-Native Task API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "req/s" }
   ]
  },
  {
   "title": "DB Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(db_latency_seconds_sum[1m]) / rate(db_latency_seconds_count[1m])",
     "legendFormat": "Avg Latency"
    },
    {
     "expr": "histogram_quantile(0.95, rate(db_latency_seconds_bucket[1m]))",
     "legendFormat": "P95 Latency"
    }
   ]
  },
  {
   "title": "DB Queries Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    { "expr": "db_latency_seconds_count", "legendFormat": "Total Queries" }
   ]
  }
 ]
}